function(ADD_C_COMPILE_OPTIONS)
  foreach (option ${ARGN})
    list(APPEND c_options $<$<COMPILE_LANGUAGE:C>:${option}>)
  endforeach()
  add_compile_options(${c_options})
endfunction()

function(ADD_CXX_COMPILE_OPTIONS)
  foreach (option ${ARGN})
    list(APPEND cxx_options $<$<COMPILE_LANGUAGE:CXX>:${option}>)
  endforeach()
  add_compile_options(${cxx_options})
endfunction()

function(ADD_ASM_COMPILE_OPTIONS)
  foreach (option ${ARGN})
    list(APPEND asm_options $<$<COMPILE_LANGUAGE:ASM>:${option}>)
  endforeach()
  add_compile_options(${asm_options})
endfunction()
